// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsUk_UX99GcOwcZrH70lC04RcsHN7aEk',
    appId: '1:260804900959:web:d2e66c6cc63e0af1c183ea',
    messagingSenderId: '260804900959',
    projectId: 'tailer-9018a',
    authDomain: 'tailer-9018a.firebaseapp.com',
    storageBucket: 'tailer-9018a.appspot.com',
    measurementId: 'G-DK2LRD0JCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NGg9vZxiikscCNA-3KOag1KaXeDXscc',
    appId: '1:260804900959:android:6bd60282305efd57c183ea',
    messagingSenderId: '260804900959',
    projectId: 'tailer-9018a',
    storageBucket: 'tailer-9018a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATE8py0P1rznNBOCKBKmjQlKo7xiEBhpc',
    appId: '1:260804900959:ios:e77b0f757408091fc183ea',
    messagingSenderId: '260804900959',
    projectId: 'tailer-9018a',
    storageBucket: 'tailer-9018a.appspot.com',
    iosBundleId: 'com.example.stitchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATE8py0P1rznNBOCKBKmjQlKo7xiEBhpc',
    appId: '1:260804900959:ios:1ed10d7b062e983dc183ea',
    messagingSenderId: '260804900959',
    projectId: 'tailer-9018a',
    storageBucket: 'tailer-9018a.appspot.com',
    iosBundleId: 'com.example.stitchApp.RunnerTests',
  );
}
